//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JointWatermark.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JointWatermark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DSC02852 {
            get {
                object obj = ResourceManager.GetObject("DSC02852", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ExifConfig {
            get {
                object obj = ResourceManager.GetObject("ExifConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Facon_2 {
            get {
                object obj = ResourceManager.GetObject("Facon_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] FZXiJinLJW {
            get {
                object obj = ResourceManager.GetObject("FZXiJinLJW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Hey_November_2 {
            get {
                object obj = ResourceManager.GetObject("Hey_November_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] leica {
            get {
                object obj = ResourceManager.GetObject("leica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] OpenSans {
            get {
                object obj = ResourceManager.GetObject("OpenSans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] OpenSans_Bold {
            get {
                object obj = ResourceManager.GetObject("OpenSans_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Pamega_demo_2 {
            get {
                object obj = ResourceManager.GetObject("Pamega_demo_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] system_b {
            get {
                object obj = ResourceManager.GetObject("system_b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] system_t {
            get {
                object obj = ResourceManager.GetObject("system_t", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 v.2.2.9.0
        ///1.新增拼图，支持多行多列
        ///2.修复BUG
        ///v.2.2.7.0
        ///1.新增图片圆角设置
        ///v.2.2.6.0
        ///1.新增LOGO导入快速入口
        ///2.新增图片横纵比设置以及全局背景颜色
        ///v.2.2.5.0
        ///1.优化元数据缺失的智能提示
        ///2.新增 导出-&gt;质量调整 记忆
        ///v.2.2.4.0
        ///1.调整软件更新功能
        ///v.2.2.3.0
        ///1.无元数据、无LOGO智能提示
        ///2.新增导出目录
        ///3.新增导出质量编辑
        ///4.导出流程优化
        ///v.2.2.2.0
        ///1.新增导出擦除元数据
        ///v.2.2.1.0
        ///1.增加导出导入快捷方式
        ///2.修复某些缺乏元数据图片导入失败的问题
        ///v.2.2.0.0
        ///1.优化UI、操作逻辑
        ///v.2.1.9.0
        ///1.新增行元数据编辑覆盖到所有图片
        ///v.2.1.8.0
        ///1.新增LOGO白底转透明像素
        ///2.手动修改元数据生效
        ///v.2.1.7.0
        ///1.LOGO可以调整大小
        ///v.2.1.4.0
        ///1.新增元数据覆盖，点击工具栏第一个按钮导入外部图片元数据覆盖当前图片
        ///2.新增程序报错自动修复功能
        ///v.2.1.3.0
        ///1.新增自动匹配LGO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
    }
}
