cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED WMI_ROOT)
  get_filename_component(WMI_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
if(NOT DEFINED WMI_DOWNLOAD_DIR)
  set(WMI_DOWNLOAD_DIR "${WMI_ROOT}/native/downloads")
endif()
if(NOT DEFINED WMI_SOURCE_DIR)
  set(WMI_SOURCE_DIR "${WMI_ROOT}/native/third_party")
endif()
if(NOT DEFINED WMI_EXTRACT)
  set(WMI_EXTRACT ON)
endif()

set(_lock_path "${WMI_ROOT}/native/dependencies.lock.json")
if(NOT EXISTS "${_lock_path}")
  message(FATAL_ERROR "Native dependency lock is missing: ${_lock_path}")
endif()
file(READ "${_lock_path}" _lock)
string(JSON _count LENGTH "${_lock}" dependencies)
math(EXPR _last "${_count} - 1")

foreach(_index RANGE 0 ${_last})
  string(JSON _name GET "${_lock}" dependencies ${_index} name)
  string(JSON _archive GET "${_lock}" dependencies ${_index} archive)
  string(JSON _directory GET "${_lock}" dependencies ${_index} sourceDirectory)
  string(JSON _expected GET "${_lock}" dependencies ${_index} sha256)
  set(_archive_path "${WMI_DOWNLOAD_DIR}/${_archive}")
  set(_source_path "${WMI_SOURCE_DIR}/${_directory}")

  if(NOT EXISTS "${_archive_path}")
    message(FATAL_ERROR
      "Missing pinned ${_name} archive: ${_archive_path}\n"
      "Application and maintainer builds never download dependencies. Place the exact archive in native/downloads.")
  endif()
  file(SHA256 "${_archive_path}" _actual)
  if(NOT _actual STREQUAL _expected)
    message(FATAL_ERROR "${_name} archive SHA-256 mismatch. Expected ${_expected}; found ${_actual}.")
  endif()

  if(WMI_EXTRACT AND NOT EXISTS "${_source_path}")
    file(MAKE_DIRECTORY "${WMI_SOURCE_DIR}")
    file(ARCHIVE_EXTRACT INPUT "${_archive_path}" DESTINATION "${WMI_SOURCE_DIR}")
  endif()
  if(WMI_EXTRACT AND NOT EXISTS "${_source_path}")
    message(FATAL_ERROR "${_name} archive did not create the locked source directory ${_source_path}.")
  endif()
  message(STATUS "Verified ${_name}: ${_expected}")
endforeach()
